package.json, script/seed.js, server/db/models/family.js, server/db/models/index.js, server/db/models/plant.js, server/db/models/species.js
=> Models seed

package.json, server/api/plant.js, server/api/plant.spec.js
=> BE: Tests written for api/plant routes.

client/components/AllPlants.js, client/routes.js
=> FE: all plants view updated

client/components/AllPlants.js, server/api/plants.spec.js
api/plant/all -----> api/plants
api/plant/:id ------> api/plants/:id
=> BE: updated test specs' routes

client/components/AllPlants.js, client/components/SinglePlant.js, client/components/navbar.js, client/routes.js, client/store/singlePlantReducer.js, public/style.css
=> FE: added route, finished component and reducer for single plant

script/seed.js, server/api/carts.js, server/api/carts.spec.js, server/api/index.js, server/db/db.js
=> Shopping cart

client/components/AllPlants.js, client/components/Cart.js, client/components/SinglePlant.js, client/index.js, client/store/cartReducer.js, package-lock.json, package.json, public/style.css
=> Shopping cart fe

server/db/models/index.js
=> BE: added Item through table

script/seed.js, server/api/carts.js, server/api/users.js, server/db/models/cart.js
=> BE: added cart routes

client/components/AllPlants.js, client/store/cartReducer.js, server/api/carts.js, server/db/db.js
FE: Hooked up new routes for shopping cart. Connected thunk in All Plants component.
=> Shopping cart routes

client/components/Checkout.js, client/components/Confirmation.js, client/routes.js
=> Fe checkout

client/components/AllPlants.js, client/components/Cart.js, client/components/Checkout.js, client/store/cartReducer.js, server/api/carts.js, server/api/checkout.js, server/api/index.js, server/api/users.js, server/db/db.js, server/db/models/cart.js, server/db/models/item.js, server/db/models/plant.js, server/db/models/type.js, server/db/models/user.js
=> Guest cart

client/components/AllPlants.js, client/components/Type.js, client/routes.js, client/store/typesReducer.js, server/api/plants.js
=> Plant type

server/db/models/cart.js
=> BE: removed unique constraint from orderId

client/components/AllPlants.js, client/components/Cart.js, client/components/Checkout.js, client/components/Confirmation.js, client/components/HomePage.js, client/components/Type.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, client/store/cartReducer.js, client/store/index.js, client/store/user-homeReducer.js, public/style.css, server/api/carts.js, server/api/checkout.js
=> Account orders

client/components/Cart.js, client/components/SinglePlant.js, client/components/Type.js, client/components/Types.js, client/components/navbar.js, client/routes.js, client/store/typesReducer.js
=> FE: types view

client/components/Type.js, client/components/Types.js, public/style.css
=> style for types

client/components/AllPlants.js, client/components/Cart.js, client/components/navbar.js, client/components/user-home.js, client/store/user.js, public/style.css, server/db/db.js
=> FE: CSS styles added

server/db/db.js
=> BE: removed db username

client/components/Types.js
=> Types Component Css

public/style.css
=> FE: CSS styling for checkout

client/components/Type.js, client/store/allplantsReducer.js, server/api/plants.js, server/db/models/plant.js
=> Fixing Types View Error

server/api/plants.js
=> changed pagination
